# Generated by Django 3.2 on 2021-04-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_crudst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crudst',
        ),
    ]
